# GitHub Pages 配置

# 站点设置
title: RXTX 中文文档
description: RXTX 是一个为 Java 提供跨平台串口和并口访问的开源库的中文文档
baseurl: "/rxtx-docs-cn"
url: "https://yeatsliao.github.io"

# 构建设置
markdown: kramdown

# 插件
plugins:
  - jekyll-seo-tag